server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:auth-db}:${DB_PORT:5432}/${DB_NAME:authdb}
    username: ${DB_USER:ducthuanle}
    password: ${DB_PASSWORD:password_ducthuanle}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    # secret phải đủ dài (>= 32 bytes)
    secret: ${JWT_SECRET}
    expiration-millis: ${JWT_EXPIRATION:3600000}
