spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:user-db}:${DB_PORT:5432}/${DB_NAME:userdb}
    username: ${DB_USER:ducthuanle}
    password: ${DB_PASSWORD:password_ducthuanle}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: ${SERVER_PORT:8081}